name: Update Coin Configs and create 128x128 images in icons dir

on:
  push:
    branches: [ "master" ]
    paths-ignore:
      - 'utils/coins_config.json'
      - 'utils/coins_config_ssl.json'
      - 'utils/coins_config_tcp.json'
      - 'utils/coins_config_wss.json'
      - 'utils/coins_config_unfiltered.json'
      - 'utils/electrum_scan_report.json'
  schedule:
    - cron:  '0 0 * * *'
  workflow_dispatch:

jobs:
  update_configs:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Install oxipng
        shell: bash
        env:
          OXIPNG_VERSION: "9.1.5"
          OXIPNG_ARCH: "x86_64-unknown-linux-gnu"
        run: |
          wget https://github.com/oxipng/oxipng/releases/download/v${OXIPNG_VERSION}/oxipng-${OXIPNG_VERSION}-${OXIPNG_ARCH}.tar.gz
          if [ $? -ne 0 ]; then
              echo "Error: Failed to download oxipng binary."
              exit 1
          fi
          tar -xzf oxipng-${OXIPNG_VERSION}-${OXIPNG_ARCH}.tar.gz
          if [ $? -ne 0 ]; then
              echo "Error: Failed to extract oxipng binary."
              exit 1
          fi
          sudo mv oxipng-${OXIPNG_VERSION}-${OXIPNG_ARCH}/oxipng /usr/local/bin/
          rm -rf oxipng-${OXIPNG_VERSION}-${OXIPNG_ARCH}.tar.gz oxipng-${OXIPNG_VERSION}-${OXIPNG_ARCH}

      - name: Create 128x128 images in icons dir
        shell: bash
        run:  ${GITHUB_WORKSPACE}/utils/icons_resize.sh

      - name: Install dependencies
        shell: bash
        run: pip3 install -r ${GITHUB_WORKSPACE}/utils/requirements.txt

      - name: Validate seed nodes
        shell: bash
        run: |
          echo "Validating seed-nodes.json before generating configs..."
          python3 ${GITHUB_WORKSPACE}/utils/validate_seed_nodes.py

      - name: Generate configs
        shell: bash
        run: ${GITHUB_WORKSPACE}/utils/generate_app_configs.py

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Update coins json file
          committer: github-actions[bot] <github-actions[bot]@users.noreply.github.com>
          author: github-actions[bot] <github-actions[bot]@users.noreply.github.com>
          branch: json-config-update
          delete-branch: true
          title: '[BOT] Update coins config json'
          body: |
            - Coins JSON config auto-generated on merge to master
            - Electrum scan report updated
            - Icon spritemap updated
          labels: |
            config-update
          reviewers: cipig, smk762, gcharang
          draft: false
